---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 10m
  chart:
    spec:
      chart: openebs
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 10m
