---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      version: 2.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    configInline:
      address-pools:
      - name: generic-cluster-pool
        protocol: layer2
        addresses:
        - 185.10.184.82-185.10.184.83
