---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-selectel
spec:
  interval: 10m
  chart:
    spec:
      chart: deploy/cert-manager-webhook-selectel
      sourceRef:
        kind: GitRepository
        name: cert-manager-webhook-selectel
        namespace: flux-system
      interval: 10m
  values:
    image:
      repository: selectel/cert-manager-webhook-selectel
      tag: "1.1.0"
