---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 30.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: prom-stack-values
      valuesKey: values.yaml
  values:
    prometheus:
      prometheusSpec:
        replicas: 2
        externalUrl: http://prom.arhilazar.ru
        retention: 1w
        ruleSelector:
          matchLabels:
            prometheus: k8s
            role: alert-rules
        resources:
          requests:
            # memory: 12000Mi
            memory: 2048Mi
            cpu: 2
      ingress:
        enabled: true
        hosts: [ "prom.arhilazar.ru" ]
        paths: [ "/" ]
        pathType: ImplementationSpecific
    alertmanager:
      ingress:
        enabled: true
        hosts: [ "alert.arhilazar.ru" ]
        paths: [ "/" ]
        pathType: ImplementationSpecific
      config:
        global:
          resolve_timeout: 6m
    grafana:
      ingress:
        enabled: true
        hosts: [ "grafana.arhilazar.ru" ]
        paths: [ "/" ]
        pathType: ImplementationSpecific
