---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 30.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 10m
  values:
    fullnameOverride: "prometheus-stack"
    grafana:
      enabled: false
    kube-state-metrics:
      fullnameOverride: "prometheus-stack-kube-state-metrics"
    prometheus-node-exporter:
      fullnameOverride: "prometheus-stack-node-exporter"
