apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: test-alerts
  namespace: monitoring
spec:
  groups:
  - name: test
    rules:
    - alert: DNS_Resolution_Issue
      annotations:
        description: a node is not able to resolve hostnames
        summary:  a node is not able to resolve hostnames
      expr: hostname_is_resolved_info < 1
      for: 5m
      labels:
        receiver: slack
