apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- helm-repos/openldap.yaml
- helm-repos/cert-manager-webhook-selectel.yaml
- helm-repos/k8s-at-home.yaml
