apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-certificates
  namespace: elk
spec:
  secretName: elastic-certificates
  isCA: false
  dnsNames:
  - "elasticsearch-master"
  issuerRef:
    name: laz-ca-issuer
    kind: ClusterIssuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password-key
        name: pkcs12-password-secret
