apiVersion: v1
kind: Secret
metadata:
    name: elastic-credentials
type: Opaque
data:
    password: ENC[AES256_GCM,data:HSMl3m26Y8VJ8/vNPiE28isxZCZGksa+tbNJtQ==,iv:N4Diad+t+F7aMboeE4HvWfHVfjEqCpDNTKxpifY4mls=,tag:akBo47vvsmfd1eB69pkr8w==,type:str]
    username: ENC[AES256_GCM,data:pTkgB3PMM4Whp1Ar,iv:EJcYiYHcdIjwMy1IDQFUvIPzkq/ZEH659leVFzN0zXo=,tag:FbPIsrEHypQ3WeLU3qeyxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-27T11:42:14Z"
    mac: ENC[AES256_GCM,data:wFflBHAOsX9E+TN4NjGFHeTgF9ku+JZQyygZ/HeVWdx5vIOmC1uNbHElAooZ/MCyaNnTdW789+KwBTF/sjP17XRdCqh/sNaZ9gXZUG64sA9gofrlWKuqrITfwDYk30hX1dM7basa5cWyyhadMEQFNrC3aGjgwQQf1SJNyVwOs+k=,iv:mAnOqDd7IgwMCPMUNgOPtchYQDjBZ/RGz6M/g7FDRdg=,tag:cQanVk/clPw0EagkC+pedA==,type:str]
    pgp:
        - created_at: "2021-09-27T11:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8+eK4ED5x4tAQ/9F0USXTUi3ZlHLUeJak6AkKPVqWVl93zv6MZd9X4bJqVs
            oEs8oHrlUMNO61lhdnX4DnO8Do+3pnRpHZTxi/gMpE53rMf73QlFXbLLfcMPjYeC
            r3/I26vhhImgXFZBiUosl6A0zEK37FXInuyMRz69FfSHEwZUdCuVjCVS+/HgPwP7
            hPxpWzngcQy/FBrxdChU0cI5Q5hvDHGUVjliCab5ccAUDczAig4Hfoqg0qqeOR9/
            TqisbbPBZAUlu4H0TyMGlv9tqd1CTjB9rIeYaxKh2QOXxjduYjg2kiDURsbQFwbd
            wE9qJ5trxg8v0du/QHEEFDFbUkPdNiD56ULTCZNQfI4NZ3ORVqZF6tE/DCHkYwzf
            q5xwq0zs6ew58qH2/92tSYJHkB3ifUUgP+nu7EkEqaNEgXtUgtLgcZ9OY9uy+M99
            8clTvzmc+HU/jgQ9ikD5+sbCdoM3WCS1m3wT70LcvLjcveZ5WmjsELXHm1pMMU6V
            G9A5uTh/keu+7S7QfbsHHJ5Bc99A/PsITHEB9PmqDipbXx2Ogo8y8B+BuNgS2U/P
            VnmqtGfD0SPdGm9xsTNdpb8vLK2Bi8FlVc2YsdRaFufAx7qEATtfThnTeDIIBZG7
            fEuTSd9OW/1uRF90M0vkKBgFTJzi/1ancBr+lXW0VNvxxtAfPpaSAAwNRB+/QNvS
            XAGPZjP/gIMTQaEv0W90PZ9ba4WBwFOpwsFrYMVv6FLKV0pmYYtF8OkdiRGdJ/G8
            Fe8au2ahvk5V6gwbMjJIefmogA7N5eBzlm7nW+QnHBUQUI03GvkfQ9dXVPKw
            =yOHF
            -----END PGP MESSAGE-----
          fp: 753E0CE636BF02F2C67F48F7848FF121DE9B079D
        - created_at: "2021-09-27T11:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwH9TgEH8JilAQ/+N1bNJtmu/KNg7pVBDtXo6x2lBguui+zyyqTQvSVmwT2l
            10VjR3+KVH2+NhPz9adxkgaMJWejipQLnUhxZ5K81K0Jpy5Ec6XpwDBYwm1+ri06
            B01n8DDJx7JfVp9jLx0tyL6LN17lFSQ7hWZQ6IB8nZKIz2gL0S5PDRqxQCDkg8NE
            OGIRHGxkQAbSARzVLqD7mg1VfMm3LuFoOmMW/08C/ETBuSXwqY4cOpCs4zBqqiI8
            pvqVgFjuK/PrOH7yDJPeCAwOSBWIroRmDoQzrl/y/7Grg3ROgV7CQhiF1azyEVq6
            k7sltshyl/nAgud4OgYM9N8K8r18q6kY3UbuaV5iCDMChZNHxH0rlsx2K//qhBtD
            D85IfUai1untaDJ5k9mZlIykrwBorfhRsG8Mowf7rlo8/I1J5gfScw72ZCxRTtPa
            oI4wD7ivJbq2Fe5M6rqPuKiRGDpeWkhMj4P9S6vb8xQziw/0LnuF7URi6Av/ZDuR
            imzln83pKKRniOOBtWZHNYku6E0Rg4CmUVau79H7IPI2Wq+cZI4SzxvH+Q05at2c
            Xl5EQBO/Eg9JXH7Qjnt8J4i8bYBTmQgrfQLSJ+bTAY+aaianVrU/963CbcQiDNvT
            nnKiD4/cu52Y0czf6dyNZRJ3igpbVYad7CR08qoGsgTt4hPzLIk3XyZH9SZ08sbS
            XAFCFu1fpFhq8sGOtQUP8aFxhNGtA4eENu7Bb51YXOD3WzBkoHgInMUh6nWRrWng
            RGhq/ACMbd+ixghwb8nGUw+5Nh8sHr6nvTSP8PTEkVFTeggHJXMHcv1lfnaR
            =NF6V
            -----END PGP MESSAGE-----
          fp: 5928D128D06253196CA5387C074F430DD9EF5AE8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kibana-encryption-key
type: Opaque
data:
    encryptionkey: ENC[AES256_GCM,data:nBbhCXUwCiqz3Zwf+B1fVb1Y4FZmty3D/RVgniXcYnZZak+CEy41LqLOmkCL5/bGefeBxhQkV/baaT2SdYbDpqQJvCQ=,iv:HjiwC1+DtVpu8deQXhHMUk16dGCAbCt+z2soU4Szrr4=,tag:jecwI9y0dg6HGjCVRZOgyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-27T11:42:14Z"
    mac: ENC[AES256_GCM,data:wFflBHAOsX9E+TN4NjGFHeTgF9ku+JZQyygZ/HeVWdx5vIOmC1uNbHElAooZ/MCyaNnTdW789+KwBTF/sjP17XRdCqh/sNaZ9gXZUG64sA9gofrlWKuqrITfwDYk30hX1dM7basa5cWyyhadMEQFNrC3aGjgwQQf1SJNyVwOs+k=,iv:mAnOqDd7IgwMCPMUNgOPtchYQDjBZ/RGz6M/g7FDRdg=,tag:cQanVk/clPw0EagkC+pedA==,type:str]
    pgp:
        - created_at: "2021-09-27T11:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8+eK4ED5x4tAQ/9F0USXTUi3ZlHLUeJak6AkKPVqWVl93zv6MZd9X4bJqVs
            oEs8oHrlUMNO61lhdnX4DnO8Do+3pnRpHZTxi/gMpE53rMf73QlFXbLLfcMPjYeC
            r3/I26vhhImgXFZBiUosl6A0zEK37FXInuyMRz69FfSHEwZUdCuVjCVS+/HgPwP7
            hPxpWzngcQy/FBrxdChU0cI5Q5hvDHGUVjliCab5ccAUDczAig4Hfoqg0qqeOR9/
            TqisbbPBZAUlu4H0TyMGlv9tqd1CTjB9rIeYaxKh2QOXxjduYjg2kiDURsbQFwbd
            wE9qJ5trxg8v0du/QHEEFDFbUkPdNiD56ULTCZNQfI4NZ3ORVqZF6tE/DCHkYwzf
            q5xwq0zs6ew58qH2/92tSYJHkB3ifUUgP+nu7EkEqaNEgXtUgtLgcZ9OY9uy+M99
            8clTvzmc+HU/jgQ9ikD5+sbCdoM3WCS1m3wT70LcvLjcveZ5WmjsELXHm1pMMU6V
            G9A5uTh/keu+7S7QfbsHHJ5Bc99A/PsITHEB9PmqDipbXx2Ogo8y8B+BuNgS2U/P
            VnmqtGfD0SPdGm9xsTNdpb8vLK2Bi8FlVc2YsdRaFufAx7qEATtfThnTeDIIBZG7
            fEuTSd9OW/1uRF90M0vkKBgFTJzi/1ancBr+lXW0VNvxxtAfPpaSAAwNRB+/QNvS
            XAGPZjP/gIMTQaEv0W90PZ9ba4WBwFOpwsFrYMVv6FLKV0pmYYtF8OkdiRGdJ/G8
            Fe8au2ahvk5V6gwbMjJIefmogA7N5eBzlm7nW+QnHBUQUI03GvkfQ9dXVPKw
            =yOHF
            -----END PGP MESSAGE-----
          fp: 753E0CE636BF02F2C67F48F7848FF121DE9B079D
        - created_at: "2021-09-27T11:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwH9TgEH8JilAQ/+N1bNJtmu/KNg7pVBDtXo6x2lBguui+zyyqTQvSVmwT2l
            10VjR3+KVH2+NhPz9adxkgaMJWejipQLnUhxZ5K81K0Jpy5Ec6XpwDBYwm1+ri06
            B01n8DDJx7JfVp9jLx0tyL6LN17lFSQ7hWZQ6IB8nZKIz2gL0S5PDRqxQCDkg8NE
            OGIRHGxkQAbSARzVLqD7mg1VfMm3LuFoOmMW/08C/ETBuSXwqY4cOpCs4zBqqiI8
            pvqVgFjuK/PrOH7yDJPeCAwOSBWIroRmDoQzrl/y/7Grg3ROgV7CQhiF1azyEVq6
            k7sltshyl/nAgud4OgYM9N8K8r18q6kY3UbuaV5iCDMChZNHxH0rlsx2K//qhBtD
            D85IfUai1untaDJ5k9mZlIykrwBorfhRsG8Mowf7rlo8/I1J5gfScw72ZCxRTtPa
            oI4wD7ivJbq2Fe5M6rqPuKiRGDpeWkhMj4P9S6vb8xQziw/0LnuF7URi6Av/ZDuR
            imzln83pKKRniOOBtWZHNYku6E0Rg4CmUVau79H7IPI2Wq+cZI4SzxvH+Q05at2c
            Xl5EQBO/Eg9JXH7Qjnt8J4i8bYBTmQgrfQLSJ+bTAY+aaianVrU/963CbcQiDNvT
            nnKiD4/cu52Y0czf6dyNZRJ3igpbVYad7CR08qoGsgTt4hPzLIk3XyZH9SZ08sbS
            XAFCFu1fpFhq8sGOtQUP8aFxhNGtA4eENu7Bb51YXOD3WzBkoHgInMUh6nWRrWng
            RGhq/ACMbd+ixghwb8nGUw+5Nh8sHr6nvTSP8PTEkVFTeggHJXMHcv1lfnaR
            =NF6V
            -----END PGP MESSAGE-----
          fp: 5928D128D06253196CA5387C074F430DD9EF5AE8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kibana-encrypted-saved-objects-encryption-key
type: Opaque
data:
    encryptionkey: ENC[AES256_GCM,data:PmwQMdTU9+fhFguPWL7uVsavNpgSDGFuaDkcOKgzE9X6YEuB06OWoFPdfnYMxEDvCb6uIF3E6xBVY5ZvwtLZ9F9MUbc=,iv:N+ui+f4uJf8DiDc/vQ0XHqgINxrgo/uufzGavDoXveQ=,tag:V0NgaJ6lYa4KPBuxxkrx2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-27T11:42:14Z"
    mac: ENC[AES256_GCM,data:wFflBHAOsX9E+TN4NjGFHeTgF9ku+JZQyygZ/HeVWdx5vIOmC1uNbHElAooZ/MCyaNnTdW789+KwBTF/sjP17XRdCqh/sNaZ9gXZUG64sA9gofrlWKuqrITfwDYk30hX1dM7basa5cWyyhadMEQFNrC3aGjgwQQf1SJNyVwOs+k=,iv:mAnOqDd7IgwMCPMUNgOPtchYQDjBZ/RGz6M/g7FDRdg=,tag:cQanVk/clPw0EagkC+pedA==,type:str]
    pgp:
        - created_at: "2021-09-27T11:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8+eK4ED5x4tAQ/9F0USXTUi3ZlHLUeJak6AkKPVqWVl93zv6MZd9X4bJqVs
            oEs8oHrlUMNO61lhdnX4DnO8Do+3pnRpHZTxi/gMpE53rMf73QlFXbLLfcMPjYeC
            r3/I26vhhImgXFZBiUosl6A0zEK37FXInuyMRz69FfSHEwZUdCuVjCVS+/HgPwP7
            hPxpWzngcQy/FBrxdChU0cI5Q5hvDHGUVjliCab5ccAUDczAig4Hfoqg0qqeOR9/
            TqisbbPBZAUlu4H0TyMGlv9tqd1CTjB9rIeYaxKh2QOXxjduYjg2kiDURsbQFwbd
            wE9qJ5trxg8v0du/QHEEFDFbUkPdNiD56ULTCZNQfI4NZ3ORVqZF6tE/DCHkYwzf
            q5xwq0zs6ew58qH2/92tSYJHkB3ifUUgP+nu7EkEqaNEgXtUgtLgcZ9OY9uy+M99
            8clTvzmc+HU/jgQ9ikD5+sbCdoM3WCS1m3wT70LcvLjcveZ5WmjsELXHm1pMMU6V
            G9A5uTh/keu+7S7QfbsHHJ5Bc99A/PsITHEB9PmqDipbXx2Ogo8y8B+BuNgS2U/P
            VnmqtGfD0SPdGm9xsTNdpb8vLK2Bi8FlVc2YsdRaFufAx7qEATtfThnTeDIIBZG7
            fEuTSd9OW/1uRF90M0vkKBgFTJzi/1ancBr+lXW0VNvxxtAfPpaSAAwNRB+/QNvS
            XAGPZjP/gIMTQaEv0W90PZ9ba4WBwFOpwsFrYMVv6FLKV0pmYYtF8OkdiRGdJ/G8
            Fe8au2ahvk5V6gwbMjJIefmogA7N5eBzlm7nW+QnHBUQUI03GvkfQ9dXVPKw
            =yOHF
            -----END PGP MESSAGE-----
          fp: 753E0CE636BF02F2C67F48F7848FF121DE9B079D
        - created_at: "2021-09-27T11:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwH9TgEH8JilAQ/+N1bNJtmu/KNg7pVBDtXo6x2lBguui+zyyqTQvSVmwT2l
            10VjR3+KVH2+NhPz9adxkgaMJWejipQLnUhxZ5K81K0Jpy5Ec6XpwDBYwm1+ri06
            B01n8DDJx7JfVp9jLx0tyL6LN17lFSQ7hWZQ6IB8nZKIz2gL0S5PDRqxQCDkg8NE
            OGIRHGxkQAbSARzVLqD7mg1VfMm3LuFoOmMW/08C/ETBuSXwqY4cOpCs4zBqqiI8
            pvqVgFjuK/PrOH7yDJPeCAwOSBWIroRmDoQzrl/y/7Grg3ROgV7CQhiF1azyEVq6
            k7sltshyl/nAgud4OgYM9N8K8r18q6kY3UbuaV5iCDMChZNHxH0rlsx2K//qhBtD
            D85IfUai1untaDJ5k9mZlIykrwBorfhRsG8Mowf7rlo8/I1J5gfScw72ZCxRTtPa
            oI4wD7ivJbq2Fe5M6rqPuKiRGDpeWkhMj4P9S6vb8xQziw/0LnuF7URi6Av/ZDuR
            imzln83pKKRniOOBtWZHNYku6E0Rg4CmUVau79H7IPI2Wq+cZI4SzxvH+Q05at2c
            Xl5EQBO/Eg9JXH7Qjnt8J4i8bYBTmQgrfQLSJ+bTAY+aaianVrU/963CbcQiDNvT
            nnKiD4/cu52Y0czf6dyNZRJ3igpbVYad7CR08qoGsgTt4hPzLIk3XyZH9SZ08sbS
            XAFCFu1fpFhq8sGOtQUP8aFxhNGtA4eENu7Bb51YXOD3WzBkoHgInMUh6nWRrWng
            RGhq/ACMbd+ixghwb8nGUw+5Nh8sHr6nvTSP8PTEkVFTeggHJXMHcv1lfnaR
            =NF6V
            -----END PGP MESSAGE-----
          fp: 5928D128D06253196CA5387C074F430DD9EF5AE8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
---
apiVersion: v1
kind: Secret
metadata:
    name: pkcs12-password-secret
type: Opaque
data:
    password-key: ENC[AES256_GCM,data:x7COat/2tmOL2lSH9ZkuTdDjP7CBtEyqaQfZOw==,iv:d8TZsjuFjdYPNkJAoodqUWYRw6UqgYxkeuuU3t/R554=,tag:wnEZGZdLRkodMumRygBASg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-27T11:42:14Z"
    mac: ENC[AES256_GCM,data:wFflBHAOsX9E+TN4NjGFHeTgF9ku+JZQyygZ/HeVWdx5vIOmC1uNbHElAooZ/MCyaNnTdW789+KwBTF/sjP17XRdCqh/sNaZ9gXZUG64sA9gofrlWKuqrITfwDYk30hX1dM7basa5cWyyhadMEQFNrC3aGjgwQQf1SJNyVwOs+k=,iv:mAnOqDd7IgwMCPMUNgOPtchYQDjBZ/RGz6M/g7FDRdg=,tag:cQanVk/clPw0EagkC+pedA==,type:str]
    pgp:
        - created_at: "2021-09-27T11:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8+eK4ED5x4tAQ/9F0USXTUi3ZlHLUeJak6AkKPVqWVl93zv6MZd9X4bJqVs
            oEs8oHrlUMNO61lhdnX4DnO8Do+3pnRpHZTxi/gMpE53rMf73QlFXbLLfcMPjYeC
            r3/I26vhhImgXFZBiUosl6A0zEK37FXInuyMRz69FfSHEwZUdCuVjCVS+/HgPwP7
            hPxpWzngcQy/FBrxdChU0cI5Q5hvDHGUVjliCab5ccAUDczAig4Hfoqg0qqeOR9/
            TqisbbPBZAUlu4H0TyMGlv9tqd1CTjB9rIeYaxKh2QOXxjduYjg2kiDURsbQFwbd
            wE9qJ5trxg8v0du/QHEEFDFbUkPdNiD56ULTCZNQfI4NZ3ORVqZF6tE/DCHkYwzf
            q5xwq0zs6ew58qH2/92tSYJHkB3ifUUgP+nu7EkEqaNEgXtUgtLgcZ9OY9uy+M99
            8clTvzmc+HU/jgQ9ikD5+sbCdoM3WCS1m3wT70LcvLjcveZ5WmjsELXHm1pMMU6V
            G9A5uTh/keu+7S7QfbsHHJ5Bc99A/PsITHEB9PmqDipbXx2Ogo8y8B+BuNgS2U/P
            VnmqtGfD0SPdGm9xsTNdpb8vLK2Bi8FlVc2YsdRaFufAx7qEATtfThnTeDIIBZG7
            fEuTSd9OW/1uRF90M0vkKBgFTJzi/1ancBr+lXW0VNvxxtAfPpaSAAwNRB+/QNvS
            XAGPZjP/gIMTQaEv0W90PZ9ba4WBwFOpwsFrYMVv6FLKV0pmYYtF8OkdiRGdJ/G8
            Fe8au2ahvk5V6gwbMjJIefmogA7N5eBzlm7nW+QnHBUQUI03GvkfQ9dXVPKw
            =yOHF
            -----END PGP MESSAGE-----
          fp: 753E0CE636BF02F2C67F48F7848FF121DE9B079D
        - created_at: "2021-09-27T11:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwH9TgEH8JilAQ/+N1bNJtmu/KNg7pVBDtXo6x2lBguui+zyyqTQvSVmwT2l
            10VjR3+KVH2+NhPz9adxkgaMJWejipQLnUhxZ5K81K0Jpy5Ec6XpwDBYwm1+ri06
            B01n8DDJx7JfVp9jLx0tyL6LN17lFSQ7hWZQ6IB8nZKIz2gL0S5PDRqxQCDkg8NE
            OGIRHGxkQAbSARzVLqD7mg1VfMm3LuFoOmMW/08C/ETBuSXwqY4cOpCs4zBqqiI8
            pvqVgFjuK/PrOH7yDJPeCAwOSBWIroRmDoQzrl/y/7Grg3ROgV7CQhiF1azyEVq6
            k7sltshyl/nAgud4OgYM9N8K8r18q6kY3UbuaV5iCDMChZNHxH0rlsx2K//qhBtD
            D85IfUai1untaDJ5k9mZlIykrwBorfhRsG8Mowf7rlo8/I1J5gfScw72ZCxRTtPa
            oI4wD7ivJbq2Fe5M6rqPuKiRGDpeWkhMj4P9S6vb8xQziw/0LnuF7URi6Av/ZDuR
            imzln83pKKRniOOBtWZHNYku6E0Rg4CmUVau79H7IPI2Wq+cZI4SzxvH+Q05at2c
            Xl5EQBO/Eg9JXH7Qjnt8J4i8bYBTmQgrfQLSJ+bTAY+aaianVrU/963CbcQiDNvT
            nnKiD4/cu52Y0czf6dyNZRJ3igpbVYad7CR08qoGsgTt4hPzLIk3XyZH9SZ08sbS
            XAFCFu1fpFhq8sGOtQUP8aFxhNGtA4eENu7Bb51YXOD3WzBkoHgInMUh6nWRrWng
            RGhq/ACMbd+ixghwb8nGUw+5Nh8sHr6nvTSP8PTEkVFTeggHJXMHcv1lfnaR
            =NF6V
            -----END PGP MESSAGE-----
          fp: 5928D128D06253196CA5387C074F430DD9EF5AE8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
