---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch-master
spec:
  interval: 10m
  chart:
    spec:
      chart: elasticsearch
      version: v7.14.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
  values:
    replicas: 3

    clusterName: "elasticsearch"
    nodeGroup: "master"

    roles:
      master: "true"
      ingest: "false"
      data: "false"
      remote_cluster_client: "false"
      ml: "false"

    volumeClaimTemplate:
      storageClassName: openebs-hostpath
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

    protocol: https

    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: true
        xpack.security.transport.ssl.enabled: true
        xpack.security.transport.ssl.verification_mode: certificate
        xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.p12
        xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
        xpack.security.transport.ssl.keystore.password: ${ELASTIC_KEYSTORE_PASSWORD}
        xpack.security.transport.ssl.truststore.password: ${ELASTIC_KEYSTORE_PASSWORD}
        xpack.security.http.ssl.enabled: true
        xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.p12
        xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
        xpack.security.http.ssl.keystore.password: ${ELASTIC_KEYSTORE_PASSWORD}
        xpack.security.http.ssl.truststore.password: ${ELASTIC_KEYSTORE_PASSWORD}
    extraEnvs:
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: password
      - name: ELASTIC_USERNAME
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: username
      - name: ELASTIC_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pkcs12-password-secret
            key: password-key

    secretMounts:
      - name: elastic-certificates
        secretName: elastic-certificates
        path: /usr/share/elasticsearch/config/certs

    ingress:
      enabled: true
      hosts:
        - host: elasticsearch.arhilazar.ru
          paths:
            - path: /
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
      - hosts:
        - elasticsearch.arhilazar.ru
        secretName: acme-ingress-elk-elasticsearch

    extraContainers:
      - name: monitoring
        image: quay.io/prometheuscommunity/elasticsearch-exporter:master
        ports:
          - containerPort: 9114
            name: metrics
            protocol: TCP
        env:
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: password
          - name: ES_USERNAME
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: username
        args:
          - '--es.uri=https://localhost:9200'
          - '--es.ssl-skip-verify'
          - '--web.listen-address=:9114'
