---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch-data
  namespace: elk
spec:
  interval: 10m
  chart:
    spec:
      chart: elasticsearch
      version: v7.13.4
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
  values:
    replicas: 5

    clusterName: "elasticsearch"
    nodeGroup: "data"
    masterService: "elasticsearch-master"

    roles:
      master: "false"
      ingest: "true"
      data: "true"
      remote_cluster_client: "true"
      ml: "true"

    volumeClaimTemplate:
      storageClassName: openebs-hostpath
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: true
        xpack.security.transport.ssl.enabled: true
        xpack.security.transport.ssl.verification_mode: certificate
        xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
        xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    extraEnvs:
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: password
      - name: ELASTIC_USERNAME
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: username

    secretMounts:
      - name: elastic-certificates
        secretName: elastic-certificates
        path: /usr/share/elasticsearch/config/certs
