---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elk
  namespace: elk
spec:
  interval: 10m
  chart:
    spec:
      chart: elasticsearch
      version: 2.4.3
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
  # values:
