---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elk
spec:
  interval: 10m
  chart:
    spec:
      chart: elasticsearch
      version: v7.13.4
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
  values:
    volumeClaimTemplate:
      storageClassName: openebs-hostpath
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

    ingress:
      enabled: true
      hosts:
        - host: elasticsearch.arhilazar.ru
          paths:
            - path: /
