---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elk
spec:
  interval: 10m
  chart:
    spec:
      chart: kibana
      version: v7.13.4
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
  values:
    replicas: 1

    elasticsearchHosts: "http://elasticsearch-master:9200"

    extraEnvs:
      - name: 'ELASTICSEARCH_USERNAME'
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: username
      - name: 'ELASTICSEARCH_PASSWORD'
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: password
      - name: 'KIBANA_ENCRYPTION_KEY'
        valueFrom:
          secretKeyRef:
            name: kibana-encryption-key
            key: encryptionkey

    kibanaConfig:
      kibana.yml: |
        xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
        elasticsearch.ssl:
          certificateAuthorities: /usr/share/kibana/config/certs/elastic-certificate.pem
          verificationMode: certificate

    secretMounts:
      - name: elastic-certificate-pem
        secretName: elastic-certificate-pem
        path: /usr/share/kibana/config/certs

    ingress:
      enabled: true
      hosts:
        - host: kibana.arhilazar.ru
          paths:
            - path: /
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
      - hosts:
        - kibana.arhilazar.ru
        secretName: acme-ingress-elk-kibana
