---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elk
spec:
  interval: 10m
  chart:
    spec:
      chart: kibana
      version: v7.13.4
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"

    ingress:
      enabled: true
      hosts:
        - host: kibana.arhilazar.ru
          paths:
            - path: /
