apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elk
resources:
- namespace.yaml
- elasticsearch-master.yaml
- elasticsearch-data.yaml
- kibana.yaml
- logstash.yaml
- creds.secret.yaml
