---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: elk
spec:
  interval: 10m
  chart:
    spec:
      chart: logstash
      version: v7.13.4
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
  values:
    service:
      ports:
        - name: http
          port: 9600
          targetPort: 9600
          protocol: TCP

    logstashConfig:
      logstash.yml: |
        http.host: 0.0.0.0
        xpack.monitoring.enabled: true
        xpack.monitoring.elasticsearch.username: '${ELASTICSEARCH_USERNAME}'
        xpack.monitoring.elasticsearch.password: '${ELASTICSEARCH_PASSWORD}'
        xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch-master:9200"]
    logstashPipeline:
      uptime.conf: |
        input { exec { command => "uptime" interval => 30 } }
        output { elasticsearch {
          hosts => ["http://elasticsearch-master:9200"]
          user => '${ELASTICSEARCH_USERNAME}'
          password => '${ELASTICSEARCH_PASSWORD}'
          index => "logstash"
          }
        }

    extraEnvs:
      - name: 'ELASTICSEARCH_USERNAME'
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: username
      - name: 'ELASTICSEARCH_PASSWORD'
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: password

    ingress:
      enabled: true
      hosts:
        - host: logstash.arhilazar.ru
          paths:
            - path: /
              servicePort: 9600
