---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: elk
spec:
  interval: 10m
  chart:
    spec:
      chart: logstash
      version: v7.13.4
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
