---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metricbeat
spec:
  interval: 10m
  chart:
    spec:
      chart: metricbeat
      version: v7.14.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 10m
  values:
    daemonset:
      hostNetworking: true

      extraEnvs:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: password
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: username
      # Allows you to add any config files in /usr/share/metricbeat
      # such as metricbeat.yml for daemonset
      metricbeatConfig:
        metricbeat.yml: |
          metricbeat.modules:
          - module: kubernetes
            metricsets:
              - container
              - node
              - pod
              - system
              - volume
            period: 10s
            host: "${NODE_NAME}"
            hosts: ["https://${NODE_NAME}:10250"]
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: "none"
            # If using Red Hat OpenShift remove ssl.verification_mode entry and
            # uncomment these settings:
            #ssl.certificate_authorities:
              #- /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            processors:
            - add_kubernetes_metadata: ~
          - module: kubernetes
            enabled: true
            metricsets:
              - event
          - module: system
            period: 10s
            metricsets:
              - cpu
              - load
              - memory
              - network
              - process
              - process_summary
            processes: ['.*']
            process.include_top_n:
              by_cpu: 5
              by_memory: 5
          - module: system
            period: 1m
            metricsets:
              - filesystem
              - fsstat
            processors:
            - drop_event.when.regexp:
                system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
          output.elasticsearch:
            username: '${ELASTIC_USERNAME}'
            password: '${ELASTIC_PASSWORD}'
            protocol: https
            hosts: ["elasticsearch-master:9200"]
            ssl.certificate_authorities:
              - /usr/share/metricbeat/config/certs/ca.crt
      secretMounts:
        - name: elastic-certificates
          secretName: elastic-certificates
          path: /usr/share/metricbeat/config/certs
