apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- helm-repos/cert-manager-webhook-selectel.yaml
- helm-repos/k8s-at-home.yaml
- helm-repos/jetstack.yaml
- helm-repos/bitnami.yaml
- helm-repos/elastic.yaml
- helm-repos/openebs.yaml
- helm-repos/ingress-nginx.yaml
