---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-ldap-tls-master
  namespace: openldap
spec:
  secretName: acme-ldap-tls-master
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - master-new.ldap.arhilazar.ru

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-ldap-tls-slave
  namespace: openldap
spec:
  secretName: acme-ldap-tls-slave
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - slave-new.ldap.arhilazar.ru
