---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-ldap-tls-master
spec:
  secretName: acme-ldap-tls-master
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - master.ldap.arhilazar.ru

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-ldap-tls-slave
spec:
  secretName: acme-ldap-tls-slave
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - slave.ldap.arhilazar.ru
