---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: openldap
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/openldap
      version: 2.1.2
      sourceRef:
        kind: GitRepository
        name: helm-openldap
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: openldap-values
      valuesKey: values.yaml
  values:
    masterReplicaCount: 2
    slaveReplicaCount: 2

    service:
      type: LoadBalancer
      master:
        loadBalancerIP: '185.10.184.83'
      slave:
        loadBalancerIP: '185.10.184.84'

    env:
      LDAP_ORGANISATION: "Selectel"
      LDAP_DOMAIN: "selectel.org"

    probes:
      ldapmodifyCheck:
        enabled: true
        baseDomain: "dc=selectel,dc=org"

    fluentd:
      enabled: true
      splunk:
        host: 185.10.184.212
        port: 8088
        insecure_ssl: true

    images:
      pullPolicy: IfNotPresent

    replication:
      enableInterServerTLS: false

    nodeSelector:
      node-role.kubernetes.io/master: ""

    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

    affinity:
      master: |
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key : "node-role.kubernetes.io/master"
                operator: Exists

      slave: |
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key : "node-role.kubernetes.io/master"
                operator: Exists


    tls:
      enabled: true
      getCertsFromCertManager: true
      secretMaster: "acme-ldap-tls-master"
      secretSlave:  "acme-ldap-tls-slave"
      CA:
        enabled: true
      files:
        common:
          dhparamPem: |
            -----BEGIN DH PARAMETERS-----
            MIIBCAKCAQEA04zCAb/x9/1GsrsmGAwBDI4ircRt3Mly5s5+nG6fHhd+CLTL0BtS
            fE9shHHqCZGoESFl4eMO1yazm5RT5TCezyqAPXtmqAw5M+JupnTbk7YRWZJHnO3D
            rDjEIaG7Q2rt6M9oHf30+kq39EjmILQ974MClLQyJkBlh8g2vfo6bFifAfyAM2HQ
            G2rM9zeH7HKaNiWPjrtVjDMyEmQ6Quor4XCdziWTZHsSOGugd1a/x+bNhJkS6K+/
            hnFawilFXgBk3p5wPmqlneY/feEI3BDVW0XboWWsHLf9u48V33sYnGH5V1ZwyyFm
            vUBSyGE8jpMy/fAvdap9RSmLupCjJKitowIBAg==
            -----END DH PARAMETERS-----
          caCrt: |
            -----BEGIN CERTIFICATE-----
            MIID/jCCAuagAwIBAgIQFaxulBmyeUtB9iepwxgPHzANBgkqhkiG9w0BAQsFADCB
            mDELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUdlb1RydXN0IEluYy4xOTA3BgNVBAsT
            MChjKSAyMDA4IEdlb1RydXN0IEluYy4gLSBGb3IgYXV0aG9yaXplZCB1c2Ugb25s
            eTE2MDQGA1UEAxMtR2VvVHJ1c3QgUHJpbWFyeSBDZXJ0aWZpY2F0aW9uIEF1dGhv
            cml0eSAtIEczMB4XDTA4MDQwMjAwMDAwMFoXDTM3MTIwMTIzNTk1OVowgZgxCzAJ
            BgNVBAYTAlVTMRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMTkwNwYDVQQLEzAoYykg
            MjAwOCBHZW9UcnVzdCBJbmMuIC0gRm9yIGF1dGhvcml6ZWQgdXNlIG9ubHkxNjA0
            BgNVBAMTLUdlb1RydXN0IFByaW1hcnkgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkg
            LSBHMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANziXmJYHTNXOTIz
            +uvLh4yn1ErdBojqZI4xmKU4kB6Yzy5jK/BGvESyiaHAKAxJcCGVn2TAppMSAmUm
            hsalifD614SgcK9PGpc/BkTVyetyEH3kMSj7HGHmKAdEc5IiaacDiGydY8hS2pgn
            5whMcD60yRLBxWeDXTPzAxHsatBT4tG6NmCUgLthY2xbF37fQJQeqw3CIShwiP/W
            JmxsYAQlTlV+fe+/lEjetx3dcI0FX4ilm/LC7urRQEFtYjgdVgbFA0dRIBn8exAL
            DmKudlW/X3e+PkkBUz2YJQN2JFodtNuJ6nnltrM7P7pMKEF/BqxqjsHQ9gUdfeZC
            huOl1UcCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
            HQYDVR0OBBYEFMR5yo6hTgMdHNxr2zFblD4/MH8tMA0GCSqGSIb3DQEBCwUAA4IB
            AQAtxRPPVoB7eni9n64smefv2t+UXglpp+duaIy9cr5HqQ6XErhK8WTTOd8lNNTB
            zU6B8A8ExCSzNJbGpqow32hhc9f5joWJ7w5elShKKiePEI4ufIbEAp7aDHdlDkQN
            kv39sxY2+hENHYwOB4lqKVb3cvTdFZx3NWZXqxNT2I7BQMXXExZacse3aQHEerGD
            AWh9jUGhlBjBJVz88P6DAod8DQ3PLghcSkANPuyBYeYk28rgDi0Hsj5W3I31QYUH
            SJsMC8tJP33st/3LjWeJGqvtux6jAAgIFyqCXDFdRootD4abdNlF+9RAsXqqaC2G
            spki4cErx5z481+oghLrGREt
            -----END CERTIFICATE-----
