---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: openldap
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/openldap
      version: 2.1.2
      sourceRef:
        kind: GitRepository
        name: helm-openldap
        namespace: flux-system
      interval: 10m
  values:
    masterReplicaCount: 2
    slaveReplicaCount: 2
    service:
      type: LoadBalancer
      master:
        loadBalancerIP: '185.10.184.83'
      slave:
        loadBalancerIP: '185.10.184.84'
    env:
      LDAP_ORGANISATION: "Selectel"
      LDAP_DOMAIN: "selectel.org"
