---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: openldap
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/openldap
      version: 2.1.2
      sourceRef:
        kind: GitRepository
        name: helm-openldap
        namespace: flux-system
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: openldap-values
      valuesKey: values.yaml
  values:
    masterReplicaCount: 2
    slaveReplicaCount: 2
    service:
      type: LoadBalancer
      master:
        loadBalancerIP: '185.10.184.83'
      slave:
        loadBalancerIP: '185.10.184.84'
    env:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Selectel"
      LDAP_DOMAIN: "selectel.org"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "tls.crt"
      LDAP_TLS_KEY_FILENAME: "tls.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      CONTAINER_LOG_LEVEL: "4"
      LDAP_TLS_REQCERT: "never"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_TLS_PROTOCOL_MIN: "3.0"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LOG_DIR: "/var/log/openldap"
      LOG_FILE: "stdout.log"

    fluentd:
      enabled: true
      splunk:
        host: 185.10.184.212
        port: 8088
        insecure_ssl: true
