apiVersion: v1
kind: Secret
metadata:
    name: openldap-values
stringData:
    values.yaml: ENC[AES256_GCM,data:duV9l+w04/h+B/2IoZ/MF6Q2bZ2I9iiHIOitBScKkJtbaZ64lwwuLoxB6JdB4iTpt9bLG4mXkSESwrZY039vFl5gXRnob1snG9UvH3XexO0hhb5eaM4RTj+ZJVJyAI2iTsDod1Ta3TwHuGDV63oR6IKfowOfKwniTYOFKpNL6M9oqcc9aKObNIe2a2qwwXK2FvuaHHsKaM8lTPrclbwxp9i1JLZGCeVhMoYXQcJvcgCefiP4grH81DrVyqjXLvDsemCr23JxRRRJiYOTTU8HSU7VlTrtm1085Zx27EhOG6xP2rBomycXBTsuBO3oeymPV7X7k6FhEE8jNlErAHNa9skYaaAqOx8GecLyp1bAflnt3dOSFfzuNTWxgvSUjx7HFk6ZAehnfCBVXUPKGFGVZf794RvZmG5q3lcfAAfmwZC5WJBIA8LgUbEOxocA57eNikxDOp9C9+3/L70+NiEUsJQ6eYn7aqoczr6idJ6UYtfnMmOLIf/YwrHtaagoGjwhTb0QyNUaSt/B/HJSGIK0y1uOhDw0ogySohEzWgF6kHbCe5oNg5sv0W39KWeSQBFFJ1w2AeotdVmvaq6SPVv/oZDmsR2pMKEOMBboNV2e162o0UQTaitX0pNAAnCUgSzcCIpQxsslU7gA,iv:SPukB5Qnbvbj2DPyENR98c/j415SrVhp9JsFN4YThfM=,tag:rYCLN46P1BgKDKPIZ1gBQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T15:27:25Z"
    mac: ENC[AES256_GCM,data:kEqBK6yQUy8ob8D11zgjdE/ywrxG7yHrf3DAzRRrVgijEXoWaG4imqwrpZRlQ0UTYmMDDS+RCTLp5LX3w1QQrVYyMTbxqpawQSzHPyjps0SSdsGtBezt0qen03URyMECg9BxALgHnBwndrA00jd36bO7777c8zO/UJcizIlBZA4=,iv:s6ilOgRuy94eCcP3Iqi/EfujAV3IGp6RENHw05I3Lbc=,tag:WwqUe3ezx4awqQonYTsoGQ==,type:str]
    pgp:
        - created_at: "2021-06-10T15:27:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6+kp2waK0pIAQ/+I1qcIZgTcFMXgks3Uz2NvdrSDCUF3h985kLsMdSWF5G2
            XZOqKiZ+SrFN7amqVMVNs/6fGgO2uaoNmmYq0iCYbpHEXmy2+TNk9PTs56WrVHf5
            Jh6Byi75aeo551eXxrQYCYaXLG+O6u7wEvC90P2Dz8+kdsqW/bjqZgW0H1IDnGPj
            n+DDdLHY2p6x0nLWreAm95U8I5DsDQVT/5PGQw2DEq0tsmJnDJRZNAYa1B3Aa+MZ
            of6l55wnoUcRD5RQuxhgiac81bhxddwxExNLnCtjfVG+ilJYesMxhfr4K311ahCh
            /JF+yPxyzdpADHS/6l3QUvYUM5DCWdWg4gf9qvA78U+t82BSR8sqhMSXy0gkTooU
            W/krHx52RSiAflJqFVlzqGC2DnomVMldozO72ErTpQRx9rld/6+BTs2J8nIp0tQ+
            yYiw6M+9pkobO6qVkVbp6cpXT33nVG+dhpazmEnTNqdd/akjqYejRiAWCnIu+4HD
            u/yuTGtJUSmOVL4I6c/MnUW3inpLB/Ayi3VCU6WQUDMjFjoRKMAjc5G3DiNUtZ+E
            scyy13UkDemK2O1MAuiiRQbuZuB7F6AxdORH4jOPsrcE0PC0z5FmaxfWsjXBAp4A
            mXLr7UZhR5Vbao1+UMCa6qzr/KWAocXjPOMBIFZIk5O59dAHJyUOEp4ZIXGTLdzS
            XgHyJHb9yOW3pTH55wpPTC8Mzk09i+04nagKE+isrsls752fk6ejKodT7wwCDIwq
            1ObWusPb6xfBF4DFlhDA/enz8c4qUOm8uOl3ZdRddJwFMSfqckOy6BwIpM25q3M=
            =fguh
            -----END PGP MESSAGE-----
          fp: 09793A927E87FDDCC57D27402BE4EF907A6424C8
        - created_at: "2021-06-10T15:27:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwH9TgEH8JilAQ/8DSm3QlofRXnHqaEOkcFw2jUyCwMHRiqX18co342ic59q
            bKEHeyCB3E4mY4jsUYZq4OmRBC6+Lg3rOlrvq/rMMqr0or8L3A7RucfxJ3hD/xxz
            /GolNAkWHYzSL5WJNFWPMFMsSPneluqPSScoHx7vWc0o8Pw/+7+w4NtKJZM0ZEGg
            yZ4zT+0mB0zidxUl0WI0KQAJQNJ/BRwb+MDNidtmRQZF+YeN5TnCYFllCS2bKsGz
            kNvGqVI+GaBGzUsn61K1wxjhD3f5FQzsnkwsLrCZD1wh4SkLSaaksvcps0q9oopY
            zP/D7ud6DKwYy5XHYzMKdSJRzsOXi+DNeSY4FnVmIuXlHUfjpWSjxZN4y0H9mgkD
            RtGK3curHMVsqvhiywYFeDK5hs3MWYJjW55WRuuJX2DT83eNlAhSED3BgvprkWXv
            jBK4vWi6enGpAU3vpzSfy98n9t0Pnq8oiH4ai5VADAX/4u021TIqkv+bPndLL02I
            BecDSYDiatZkyjJwzUBoeP9JIxPTlXs36wJvZVnNKTxbhUblvrZJEK5d31zMbCDP
            FPlEflyXiubRWMWH7VqUlsUWHWzX4kqnsOZghx2zJ6MgyhWiizbjXf3a1SMkYwhp
            4BF9Eva6qt78My4sIWHeQpCz7mP5tpXzv7RtPbU424fx5VJ4HemK76d/zK9r6kvS
            XgHeFmis70aLfvrQn2Kkacci9BqK/DstcLu76W1neZ2WHcBjOTdTuDLMVsjMvdv9
            qOSOcw3AHhJIsMmPRv2HSZDB6hkCZe4jW0UxLFOlCotbrjcPPYhD/ge/Qcs5DTk=
            =9CVf
            -----END PGP MESSAGE-----
          fp: 5928D128D06253196CA5387C074F430DD9EF5AE8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
