apiVersion: v1
kind: Secret
metadata:
    name: openldap-values
stringData:
    values.yaml: ENC[AES256_GCM,data:M2Td6MgPjUdVR+rxGHzou0Gy/vBRXo1IisTHbYEfjZw09zADfD/Ehq1Xq+yRoPzhUNjpbG0Adaon6Se2YSxQCQHFGLCAvcczvs48M60szaM0fPFUOzM0Loxc5L/q9/6u2wwU/yLiclmp/CcOjg/UJIHFmMLq7fVt2iYYsGroQBGybFjO4bcHxy4AFab+A/G/6/2kHRkT992/AXHL8+0iBQFktL+Mec1JZdtv6nqvfbFWOdeZr4Lrk+ni0s3i1nL0smfQTuLJcpO8XhxestqQCkeUYOZ/09WO8lgr0BUj3jTrvafN/ghzZghNuqP3qU2bj51k63x8/BQvthwYOuQEIOx26qDvegKO5GaLwvEByM439LLVafV42G29LJmKguk6RWamwg+5m+ycUkrQ/RfkWdfhTALdF0Tx55J6Zyy48AMjfVdpqr/E8o0SD9w72Grboux02qS2imXUPpqUzURxAcogP5zYdMyJJxxIWkRMP0NhtNVT0e6MdimnrnTM7AC1gyNKlA6U8B7uHVshns6PElVox6L7OgZxUsnCy8l3dJOm7iN3iyu0ypx/M4L+FK+t4II8S3D/TqIR42fUsU5Vh1PDbs2ALawDpFOmlB945EtdQ7cTZ4TqRcr7s1ghtGFm1u/DJwsPRZ5Uy6rnig==,iv:HrTeM68Iku76JGTMGmBltwrt9tKUAPQNUlnONWdgI0U=,tag:4jSJufmHO47boBrrzUoT1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T14:43:54Z"
    mac: ENC[AES256_GCM,data:7kAiVvhOzOQ93whgNn9ZKPS+Ta7an6sWPbZeKoCPrkeqUy8PEszlyzkTiu4U/aS1flvg7FQAeucOfI1oV25Ny4JXS6yw+uJox73R6LHTPDmj75CnV1poo5NNM4cEKsQvZYs4oZu287LWd6cojgNE4VHh/R24rHtxeK51NGPC9Cc=,iv:UF+U5SctOdpkK5ASC95bQ5Kl/GhjhIR7EqgXCb7X4MM=,tag:Bpbu0blN8nWhYD+Gw7bLfg==,type:str]
    pgp:
        - created_at: "2021-06-10T14:43:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6+kp2waK0pIAQ/9HA/mlg7RMtwqrMSGHU5naQthQGsZqLYfyU0dNIyOgIFD
            aMm4vpP3pxYsxdEKIPr/GY6LGVKpiQ9MeBqg8DPwlNcXwsumG274W6QOXJfa8dmy
            T/f2txC2Ewr2T2pSedAa2QCJ/YjBXDOKwXr01Sdx62X6EScmLeiX2gYJZraxy8bH
            HAkb5jLMSUY6YITKUeOXVmNmXxrXwqHSDWDZapqX0kw08z68RvfAH4K4ZOyzfx5k
            X+6EL1ga60LH2wJjcnE4H0tpWsJ56u7Zhkl56HrJiOOXsIN4vEEAgwF09vpj1xC2
            P8UGClX2pKv91Lfk7X+XTzz4O7BfzzKLmLue8Ma9UoRhZ19kiyuZ2ANJCk1kgheX
            sq6ambAmP7aatsG2nBX2B2eN2J1xO9wzADMDGwCHoS84aNOSPTEXcUBY/M+hEAgq
            wsaZcYLK46CTnq6Is3ALklCDDdduRy6s9Z3bv4mMX7whIUvGAagD6yHiOM16N73K
            t5SkFreFt+3Fftkid+XjubAT1RVCZCpyPJkl4X6X9LW6OxYuq/We7TpBkiyqskrd
            jNkVdzZx0akcMojxMllKcXnID/huLsUSU1tE6sneOZjpsObZMzb5Lcttn4BxEme1
            0IHntKzbAzz6aP7Ifyj4WRxR6XBmw0FPQHaGM8TXq5pGcW8hrN76VI/ByqUumhjS
            XgFRrkluNh+qMk6X9moHtvXQfa2tV6VlTxG70RnFSeY5kPYpVd58+H1Ff/5USgsf
            Ng7xNYb6aijcL450LS7qqb7DoadJUgO9g1kQpK8S+WICloYw+Ha7qJUXprUrYMQ=
            =vG9S
            -----END PGP MESSAGE-----
          fp: 09793A927E87FDDCC57D27402BE4EF907A6424C8
        - created_at: "2021-06-10T14:43:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwH9TgEH8JilAQ//Zcqxktcpj5NModBitLx7vedWxMNCtJE9TOsDZGMqWnkD
            Qnf/zUl4UfIprxTPs4Yn/11lgcvrj7TictAkOhp5cLsNgChtKFfDfbCt+nSvop2h
            WOU+PV54pOqMxnTBMvhk83CWuMido23LVn3MkmHd5AQhw6+26hUZM8Xvgy0FBYpp
            F+wpNDy1tdFlex8QxMuS0M/iGDaZgKsP3XhrMZc4Ac5/DQ9+DryJmJOVh07Fvh8J
            xWENk7XngLz+jzYODQnNGVa3wxu0ZKHjkbuT9wHcyanN8V8JwWtaQ5bw1tE7cWVL
            BOiWcW6IgS76WYwXMXoLMTmwghgZhm5fGpZ26M5r+SBFmR54q758CmUembpniA04
            ea5wK27hUYI2HcLlREtkMUQLAktJGQpLz6U3yvoJ/t/WIYY/Y33+BQZORw5Dcy1K
            JUjEADusTKu9hjVBxu/OT5S7cWJnjM3s94UldkMYOzeLM3WGHN2ht0d2+GMpwukq
            ZoWkmrtstM/8Mv/eEniQeqZo/BqWD8Mv8sKCYj3BLxxNP+nouXJg78O8w5VYSt+w
            Bn7KljIC1w0kEp3pNXC7th3ii52EX5TiNMCyWNYWa+k/k84cDzccc8O9p8Afnn2e
            kPT+fb/ndtDa9Qkt+wGXJ448+TQBbvT9UFv5u4nw0GWiOy6C6xRaPIA9QUq4gn3S
            XgFDXd0oV6LV8bHL9qAXmGlNfPeUeav7QVFnvpwgN4Dyh2Zz9housndf5h/QYyFj
            uidqpF5mZ9+8Akdq9jvtgmLfq0vNPXhNsn0aP1a4bbCqj0b752NPnASxPLcq60Q=
            =V7H6
            -----END PGP MESSAGE-----
          fp: 5928D128D06253196CA5387C074F430DD9EF5AE8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
