---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 10m
  chart:
    spec:
      chart: metrics-server
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 10m
  values:
    args:
      - --kubelet-insecure-tls
